name: enterprise_data_migration
version: '1.0.0'
config-version: 2

profile: enterprise_data_migration

model-paths: [models]

models:
  enterprise_data_migration:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
